# Please keep it valid for Rake & minirake simultaneously.

task :default => ['mruby', :setup, :compile]

unless ENV['COMMIT']
  # last known 'good' commit id
  ENV['COMMIT'] = 'd23bc85b546af771b875f2ae3beaaa5c141683db'
end

# clone repo
file 'mruby' do |t|
  sh "git clone git@github.com:mruby/mruby.git"
  if ENV['COMMIT'] != ''
    Dir.chdir 'mruby' do
      sh "git checkout #{ENV['COMMIT']}"
    end
  end
end

patch="conf.gem :core => 'mruby-eval'; conf.gembox '#{File.realpath('minirake.gembox').ext ''}'"

task :setup do
  if `grep minirake mruby/build_config.rb` == ""
    sh "sed -i \"/conf.gembox 'default'/a #{patch}\" mruby/build_config.rb"
    sh "patch -p0 -b < mrbc.patch"
  end
end

task :compile do
  Dir.chdir 'mruby' do
    sh "make clean"
    sh "make"
  end
end



task :clean do
  rm_rf 'mruby'
end
