includes = '-I ../mruby/mruby/include'
static = '../mruby/mruby/build/host/lib/libmruby.a'
libs = '-lm -ldl -lyaml -lpthread'
mrbc = '../mruby/mruby/bin/mrbc'

task :default => ['minirake']

obj = Dir.glob('*.c').map {|i| i.ext '.o'}

file 'minirake' => obj.push('bytecode.o') do |t|
  sh "cc -Wall #{t.prerequisites.join ' '} #{static} -o #{t.name} #{libs}"
end

file 'bytecode.c' => ['ruby/minirake.rb'] do |t|
  sh "#{mrbc} -B bytecode -o #{t.name} #{t.prerequisites[0]}"
end

rule '.o' => ['.c'] do |t|
  sh "cc -Wall #{t.source} -c -o #{t.name} #{includes}"
end



task :clean do
  sh "rm -f bytecode.[co] #{obj.join ' '} minirake"
end
